export const USER_INFO = "USER_INFO";
export const INSTITUTION_INFO = "INSTITUTION_INFO";
export const ACADAMIC_DATA = "ACADAMIC_DATA";
export const TOKEN = "TOKEN";
export const ACADEMIC_SESSION_DATA = "ACADEMIC_SESSION_DATA";
export const ACADEMIC_SESSION_INFO = "ACADEMIC_SESSION_INFO";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const AUTHENTICATION = "AUTHENTICATION";




